sudo: required  
services:  
  - docker

script:
  - docker build -t beget/sprutio-python:$TRAVIS_BRANCH -f Dockerfile ./
  - docker build -t beget/sprutio-cron:$TRAVIS_BRANCH -f Dockerfile.cron ./
  - docker build -t beget/sprutio-bower:$TRAVIS_BRANCH -f Dockerfile.bower ./
  - docker build -t beget/sprutio-rpc:$TRAVIS_BRANCH -f rpc/Dockerfile rpc/
  - docker build -t beget/sprutio-app:$TRAVIS_BRANCH -f app/Dockerfile app/
  - docker build -t beget/sprutio-nginx:$TRAVIS_BRANCH -f Dockerfile.nginx ./
  - docker run -v $PWD/app/public:/app -w /app beget/sprutio-bower:$TRAVIS_BRANCH bower install --allow-root
  - docker build -t beget/sprutio-frontend:$TRAVIS_BRANCH -f app/public/Dockerfile app/public/

after_success:
  - docker login --email=$DOCKER_HUB_EMAIL --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
  - docker push beget/sprutio-cron:$TRAVIS_BRANCH
  - docker push beget/sprutio-rpc:$TRAVIS_BRANCH
  - docker push beget/sprutio-app:$TRAVIS_BRANCH
  - docker push beget/sprutio-nginx:$TRAVIS_BRANCH
  - docker push beget/sprutio-frontend:$TRAVIS_BRANCH

